//  ================================================================
//  Created by Gregory Kramida on 1/2/20.
//  Copyright (c) 2020 Gregory Kramida
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at

//  http://www.apache.org/licenses/LICENSE-2.0

//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//  ================================================================
#pragma once
  
#define ITM_SERIALIZATION_IMPL_IIF2(c) ITM_SERIALIZATION_IMPL_CAT(ITM_SERIALIZATION_IMPL_IIF2_, c)
#define ITM_SERIALIZATION_IMPL_IIF2_0(t, f) f
#define ITM_SERIALIZATION_IMPL_IIF2_1(t, f) t

#define ITM_SERIALIZATION_IMPL_CHECK_N2(x, n, ...) n
#define ITM_SERIALIZATION_IMPL_CHECK2(...) ITM_SERIALIZATION_IMPL_CHECK_N2(__VA_ARGS__, 0, )
#define ITM_SERIALIZATION_IMPL_PROBE2(x) x, 1,

#define ITM_SERIALIZATION_IMPL_IS_PAREN2(x)                                             \
  ITM_SERIALIZATION_IMPL_CHECK2(ITM_SERIALIZATION_IMPL_IS_PAREN_PROBE2 x)
#define ITM_SERIALIZATION_IMPL_IS_PAREN_PROBE2(...) ITM_SERIALIZATION_IMPL_PROBE2(~)

#define ITM_SERIALIZATION_IMPL_SIMPLE_PASTE2(...) __VA_ARGS__
#define ITM_SERIALIZATION_IMPL_SIMPLE_RECOMBINE2(C, x) (C, ITM_SERIALIZATION_IMPL_SIMPLE_PASTE2 x)

#define ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x)                                                                       \
  ITM_SERIALIZATION_IMPL_IIF2(ITM_SERIALIZATION_IMPL_IS_PAREN2(x))                                                   \
  (M ITM_SERIALIZATION_IMPL_SIMPLE_RECOMBINE2 (C, x), M (C,x))

#define ITM_SERIALIZATION_IMPL_LOOP2_1(M, C, D, x) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x)

#define ITM_SERIALIZATION_IMPL_LOOP2_2(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                              \
  ITM_SERIALIZATION_IMPL_LOOP2_1(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_3(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                              \
  ITM_SERIALIZATION_IMPL_LOOP2_2(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_4(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                              \
  ITM_SERIALIZATION_IMPL_LOOP2_3(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_5(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                              \
  ITM_SERIALIZATION_IMPL_LOOP2_4(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_6(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                              \
  ITM_SERIALIZATION_IMPL_LOOP2_5(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_7(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                              \
  ITM_SERIALIZATION_IMPL_LOOP2_6(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_8(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                              \
  ITM_SERIALIZATION_IMPL_LOOP2_7(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_9(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                              \
  ITM_SERIALIZATION_IMPL_LOOP2_8(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_10(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_9(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_11(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_10(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_12(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_11(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_13(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_12(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_14(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_13(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_15(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_14(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_16(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_15(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_17(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_16(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_18(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_17(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_19(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_18(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_20(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_19(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_21(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_20(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_22(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_21(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_23(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_22(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_24(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_23(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_25(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_24(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_26(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_25(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_27(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_26(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_28(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_27(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_29(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_28(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_30(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_29(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_31(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_30(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_32(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_31(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_33(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_32(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_34(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_33(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_35(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_34(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_36(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_35(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_37(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_36(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_38(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_37(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_39(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_38(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_40(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_39(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_41(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_40(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_42(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_41(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_43(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_42(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_44(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_43(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_45(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_44(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_46(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_45(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_47(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_46(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_48(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_47(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_49(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_48(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_50(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_49(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_51(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_50(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_52(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_51(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_53(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_52(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_54(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_53(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_55(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_54(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_56(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_55(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_57(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_56(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_58(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_57(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_59(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_58(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_60(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_59(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_61(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_60(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_62(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_61(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_63(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_62(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_64(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_63(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_65(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_64(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_66(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_65(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_67(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_66(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_68(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_67(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_69(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_68(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_70(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_69(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_71(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_70(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_72(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_71(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_73(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_72(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_74(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_73(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_75(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_74(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_76(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_75(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_77(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_76(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_78(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_77(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_79(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_78(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_80(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_79(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_81(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_80(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_82(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_81(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_83(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_82(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_84(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_83(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_85(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_84(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_86(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_85(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_87(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_86(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_88(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_87(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_89(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_88(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_90(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_89(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_91(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_90(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_92(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_91(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_93(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_92(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_94(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_93(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_95(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_94(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_96(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_95(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_97(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_96(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_98(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_97(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_99(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                             \
  ITM_SERIALIZATION_IMPL_LOOP2_98(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_100(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_99(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_101(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_100(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_102(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_101(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_103(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_102(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_104(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_103(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_105(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_104(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_106(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_105(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_107(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_106(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_108(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_107(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_109(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_108(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_110(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_109(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_111(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_110(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_112(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_111(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_113(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_112(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_114(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_113(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_115(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_114(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_116(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_115(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_117(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_116(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_118(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_117(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_119(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_118(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_120(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_119(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_121(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_120(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_122(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_121(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_123(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_122(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_124(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_123(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_125(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_124(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_126(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_125(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_127(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_126(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_128(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_127(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_129(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_128(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_130(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_129(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_131(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_130(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_132(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_131(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_133(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_132(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_134(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_133(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_135(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_134(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_136(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_135(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_137(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_136(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_138(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_137(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_139(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_138(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_140(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_139(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_141(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_140(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_142(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_141(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_143(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_142(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_144(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_143(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_145(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_144(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_146(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_145(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_147(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_146(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_148(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_147(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_149(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_148(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_150(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_149(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_151(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_150(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_152(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_151(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_153(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_152(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_154(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_153(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_155(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_154(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_156(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_155(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_157(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_156(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_158(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_157(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_159(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_158(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_160(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_159(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_161(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_160(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_162(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_161(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_163(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_162(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_164(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_163(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_165(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_164(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_166(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_165(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_167(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_166(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_168(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_167(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_169(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_168(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_170(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_169(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_171(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_170(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_172(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_171(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_173(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_172(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_174(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_173(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_175(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_174(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_176(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_175(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_177(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_176(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_178(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_177(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_179(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_178(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_180(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_179(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_181(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_180(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_182(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_181(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_183(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_182(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_184(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_183(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_185(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_184(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_186(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_185(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_187(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_186(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_188(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_187(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_189(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_188(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_190(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_189(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_191(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_190(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_192(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_191(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_193(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_192(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_194(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_193(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_195(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_194(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_196(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_195(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_197(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_196(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_198(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_197(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_199(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_198(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_200(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_199(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_201(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_200(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_202(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_201(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_203(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_202(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_204(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_203(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_205(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_204(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_206(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_205(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_207(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_206(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_208(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_207(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_209(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_208(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_210(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_209(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_211(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_210(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_212(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_211(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_213(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_212(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_214(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_213(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_215(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_214(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_216(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_215(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_217(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_216(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_218(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_217(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_219(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_218(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_220(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_219(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_221(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_220(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_222(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_221(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_223(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_222(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_224(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_223(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_225(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_224(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_226(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_225(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_227(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_226(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_228(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_227(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_229(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_228(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_230(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_229(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_231(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_230(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_232(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_231(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_233(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_232(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_234(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_233(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_235(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_234(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_236(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_235(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_237(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_236(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_238(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_237(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_239(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_238(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_240(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_239(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_241(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_240(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_242(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_241(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_243(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_242(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_244(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_243(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_245(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_244(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_246(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_245(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_247(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_246(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_248(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_247(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_249(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_248(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_250(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_249(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_251(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_250(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_252(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_251(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_253(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_252(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_254(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_253(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_255(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_254(M, C, D, __VA_ARGS__)

#define ITM_SERIALIZATION_IMPL_LOOP2_256(M, C, D, x, ...) ITM_SERIALIZATION_IMPL_UNPACK2(M, C, x) D()                            \
  ITM_SERIALIZATION_IMPL_LOOP2_255(M, C, D, __VA_ARGS__)


